# Generated by Django 5.0.6 on 2025-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_productenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode number (UPC, EAN, etc.)', max_length=50, null=True, unique=True),
        ),
    ]
