# Generated by Django 5.2.3 on 2025-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cash amount for split payments', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Other payment method amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='other_method',
            field=models.CharField(blank=True, help_text='Description of other payment method', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pos_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='POS/Card amount for split payments', max_digits=10),
        ),
    ]
