# Generated by Django 5.0.6 on 2025-06-21 10:29

from django.db import migrations

def set_default_prices(apps, schema_editor):
    Product = apps.get_model('portal', 'Product')
    for product in Product.objects.filter(cost_price__isnull=True):
        product.cost_price = 0
    for product in Product.objects.filter(selling_price__isnull=True):
        product.selling_price = product.price if hasattr(product, 'price') else 0
    Product.objects.bulk_update(Product.objects.all(), ['cost_price', 'selling_price'])

class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_product_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_prices),
    ]
