# Generated by Django 5.0.6 on 2025-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_set_default_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='products/'),
        ),
    ]
