# Generated by Django 5.0.6 on 2025-06-21 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Percentage'), ('amount', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
