# Generated by Django 5.2.3 on 2025-07-02 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_cart_site_cartitem_site_order_site'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='selling_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='portal.category'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-desktop', 'Computer Hardware'), ('fa-microchip', 'Electronic Components'), ('fa-network-wired', 'Networking'), ('fa-tools', 'Tools'), ('fa-print', 'Printers & Scanners'), ('fa-mobile-alt', 'Mobile Devices'), ('fa-shield-alt', 'Security'), ('fa-server', 'Servers'), ('fa-hdd', 'Storage'), ('fa-headset', 'Peripherals')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
