# Generated by Django 5.0.6 on 2025-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_unit_price_invoiceitem_selling_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
