# Generated by Django 5.0.6 on 2025-06-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_invoiceitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
