# Generated by Django 5.2.3 on 2025-07-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_sitepermissionlog_siterole_siteuserprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siterole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='siterole',
            name='site',
        ),
        migrations.RemoveField(
            model_name='siteuserprofile',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='siteuserprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='siteuserprofile',
            name='site',
        ),
        migrations.RemoveField(
            model_name='siteuserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SitePermissionLog',
        ),
        migrations.DeleteModel(
            name='SiteRole',
        ),
        migrations.DeleteModel(
            name='SiteUserProfile',
        ),
    ]
