# Generated by Django 5.2.3 on 2025-07-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_siterole_unique_together_remove_siterole_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='selling_price',
        ),
    ]
