# Generated by Django 5.2.3 on 2025-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_rename_unit_price_invoiceitem_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='selling_price',
            new_name='unit_price',
        ),
    ]
