# Generated by Django 5.2.3 on 2025-07-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_rename_selling_price_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='unit_price',
        ),
    ]
