# Generated by Django 5.0.6 on 2025-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_invoiceitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
