# Generated by Django 5.2.3 on 2025-07-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_fix_invoice_number_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_reports', 'Can view reports'), ('access_analytics', 'Can access analytics API')]},
        ),
    ]
