# Generated by Django 5.2.3 on 2025-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_customer_options'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number',), name='unique_invoice_number'),
        ),
    ]
