# Generated by Django 5.2.3 on 2025-09-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_invoice_status'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='use_product_price',
            field=models.BooleanField(default=True, help_text="If True, uses product's unit price. If False, allows custom price."),
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of sale', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='portal.invoice')),
                ('product', models.ForeignKey(blank=True, help_text='Reference to original product (may be null if product deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.product')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Sold Item',
                'verbose_name_plural': 'Sold Items',
                'ordering': ['-date_sold'],
            },
        ),
    ]
