# Generated by Django 5.2.3 on 2025-09-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_invoiceitem_use_product_price_solditem'),
    ]

    operations = [
    ]
