# Generated by Django 5.2.3 on 2025-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_cart_session_key_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Arabic)'),
        ),
    ]
