# Generated by Django 5.2.3 on 2025-09-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('daily_cash_sales', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Cash sales for the day', max_digits=12)),
                ('daily_pos_sales', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: POS/Card sales for the day', max_digits=12)),
                ('daily_service_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Service revenue for the day', max_digits=12)),
                ('daily_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Manual entry: Purchase expenses for the day', max_digits=12)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated: Cash Sales + POS Sales + Service Revenue - Purchase', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Daily notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_count', models.IntegerField(default=0, help_text='Number of times printed')),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('last_printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_revenue_prints', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site')),
            ],
            options={
                'verbose_name': 'Daily Revenue',
                'verbose_name_plural': 'Daily Revenues',
                'ordering': ['-date', 'site'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
