# Generated by Django 5.2.3 on 2025-07-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['site', 'type', 'name'], 'verbose_name_plural': 'Finance Categories'},
        ),
        migrations.AlterModelOptions(
            name='financetransaction',
            options={'ordering': ['-date', 'site'], 'verbose_name': 'Finance Transaction', 'verbose_name_plural': 'Finance Transactions'},
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('site', 'name', 'type')},
        ),
    ]
