# Generated by Django 5.2.3 on 2025-07-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_site_awareness'),
        ('portal', '0015_alter_customer_options'),
        ('procurement', '0003_alter_purchasepayment_options_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Auto-generated from other apps'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the source record (Invoice, PO, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('invoice', 'Sales Invoice'), ('purchase_order', 'Purchase Order'), ('purchase_payment', 'Purchase Payment')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Credit Card'), ('pos', 'POS'), ('split', 'Split Payment'), ('other', 'Other')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('expense', 'Expense'), ('purchase_payment', 'Purchase Payment'), ('sale_receipt', 'Sale Receipt')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='financetransaction',
            unique_together={('source_type', 'source_id', 'site')},
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('adjustment', 'Stock Adjustment'), ('return', 'Return')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procurement.purchaseorder')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-date', 'site'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchase_orders', models.PositiveIntegerField(default=0)),
                ('total_purchase_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cash_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site')),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-year', '-month', 'site'],
                'unique_together': {('site', 'year', 'month')},
            },
        ),
    ]
