# Generated by Django 5.2.3 on 2025-07-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financetransaction_auto_generated_and_more'),
        ('portal', '0015_alter_customer_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financetransaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if auto-generated from procurement/sales'),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('pos', 'POS'), ('bank', 'Bank Transfer'), ('transfer', 'Transfer'), ('card', 'Credit Card'), ('other', 'Other')], default='bank', max_length=10),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='Source model ID', null=True),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='source_type',
            field=models.CharField(blank=True, help_text='Source model type (invoice, purchase_order, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='financetransaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('purchase_payment', 'Purchase Payment'), ('sale', 'Sale'), ('sale_receipt', 'Sale Receipt'), ('expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialsummary',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='financialsummary',
            name='total_invoices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialsummary',
            name='total_purchase_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialsummary',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.product'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=20),
        ),
    ]
