# Generated by Django 5.2.3 on 2025-07-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_emailverification'),
    ]

    operations = [
    ]
