# Generated by Django 5.2.3 on 2025-07-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at', 'site'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['site', 'name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='sites.site'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('site', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('site', 'name')},
        ),
    ]
