# Generated by Django 5.2.3 on 2025-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_add_site_awareness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Purchase Payment', 'verbose_name_plural': 'Purchase Payments'},
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount due for this purchase order', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date', null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('transfer', 'Bank Transfer'), ('card', 'Credit Card'), ('other', 'Other')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Bank reference, cheque number, etc.', max_length=100),
        ),
    ]
